version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: resepUser
      POSTGRES_PASSWORD: resepkunjir
      POSTGRES_DB: resepku
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://resepUser:resepkunjir@db:5432/resepku
    depends_on:
      - public-uploads:/public/uploads
      - db
    env_file:
      - .env

volumes: 
  postgres-data:
  public-uploads:

