version: '3.8'
services:
  db:
    image: postgres
    restart: always
environment:
  POSTGRES_USER: resepUser
  POSTGRES_PASSWORD: resepkunjir
  POSTGRES_DB: resepku
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgres://postgres:postgres@db:5432/myrecipes
    depends_on:
      - db
    command: sh -c "npx prisma generate && npm run dev"

volumes: 
  postgres-data:
